[package]
name = "horsenuggets/t"
description = "A Runtime Typechecker for Roblox"
version = "3.1.1-horse.0.3"
license = "MIT"
authors = ["Osyris"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["*"]
include = [
    ".luaurc",
    "default.project.json",
    "init.luau",
    "lib",
    "lib/init.lua",
    "LICENSE",
    "README.md",
    "wally.toml",
]

[dependencies]
