[package]
name = "horsenuggets/t"
description = "A Runtime Typechecker for Roblox"
version = "3.1.1-horse.0.4"
license = "MIT"
authors = ["Osyris"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["*"]
include = [
    ".luaurc",
    "default.project.json",
    "init.luau",
    "LICENSE",
    "README.md",
    "Source",
    "Source/**",
    "wally.toml",
]

[dependencies]

[dev-dependencies]
Testable = "horsenuggets/testable@1.1.3"
